site_name: cloudlabmp
site_url: https://blog.pollockweb.com/
#site_url: https://cloudlabmp.github.io/project-blog
#site_url: https://127.0.0.1/project-blog
site_author: matt.pollock@outlook.com (Matthew Pollock)
site_description: A blog about tech stuff
repo_url: https://github.com/cloudlabmp/project-blog
repo_name: "cloudlabmp/project-blog"

nav:
  - Blog:
      - Posts: blog/index.md
      - Tags: blog/tags.md
  - Learn: learn.md
  - About: about.md
  - Work: work.md

theme:
  name: material
  custom_dir: overrides
  logo: assets/icons/logo-48x48.png
  favicon: assets/icons/favicon.ico
  features:
    - navigation.indexes
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - content.code.select
    - content.code.copy
    - announce.dismiss

  palette:
    # Dark Mode (Forced as Default)
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
      primary: deep orange
      accent: deep purple

    # Light Mode (Optional)
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: blue
      accent: deep orange

plugins:
  - search
  - glightbox:
      zoomable: true
  
  - blog:
      blog_dir: blog
      blog_toc: true
      categories_toc: true
      archive_toc: true
      authors_file: authors.yml
      archive: true
      archive_name: Posts
      post_url_format: "{slug}"

  - tags:
      tags_file: blog/tags.md
      
  - rss:
      match_path: "posts/.*"
      date_from_meta:
        as_creation: date.created
        as_update: date.updated
      use_git: false  # Added to prevent the warning

  - git-committers:
      enabled: true
      repository: cloudlabmp/project-blog
      branch: main
      token: !ENV MKDOCS_GIT_COMMITTERS_APIKEY

  - git-revision-date-localized:
      type: date
      fallback_to_build_date: false
      enable_creation_date: true
      enabled: true
  
extra:
  homepage: https://cloudlabmp.github.io/project-blog/blog/welcome-to-my-blog/
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/cloudlabmp
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/matthew-pollock-76831920/
    - icon: fontawesome/solid/globe
      link: https://profile.pollockweb.com
  analytics:
    provider: google
    property: G-800NGKWBYL
    

hooks:
  - hooks/socialmedia.py

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  
extra_css:
    - stylesheets/extra.css

copyright: Copyright &copy; 2025 Matthew Pollock
